services:
  db-service:
    image: postgres:latest
    restart: always
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db-service
    env_file:
      - db.env
      - app.env
    ports:
      - "8001:8080"
    restart: always


volumes:
  db_data:
